=== yaraGamal7/XML-Tasks/DAY1/dtd of fmaily.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT family ( grandfather ) >
<!ELEMENT grandfather (father , uncle+ , anut ) > 
<!ELEMENT uncle ( #PCDATA ) >
<!ELEMENT anut ( #PCDATA ) >
<!ELEMENT father ( son , daughter , mother ) >
<!ELEMENT son ( #PCDATA ) >
<!ELEMENT daughter ( #PCDATA ) >
<!ELEMENT mother ( #PCDATA ) >




<!ATTLIST father job (Engineer |  Accountant | Doctor) "Engineer" >
<!ATTLIST son age  CDATA #REQUIRED sport ( tennis | football ) "football" >
<!ATTLIST daughter job (Engineer |  Accountant | Doctor) "Engineer" age  CDATA #REQUIRED >
<!ATTLIST aunt sons NMTOKEN #IMPLIED >

=== yaraGamal7/XML-Tasks/DAY1/family.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE family SYSTEM "C:\Users\Yara\Desktop\task xml\dtd of fmaily.dtd">

<family>
	<grandfather>
		<father job="Doctor">
		
			<son age="10" sport="tennis" > ahmed  </son>
			<daughter age="10"> yara </daughter>
			<mother> amina </mother>
		</father>
		
		<uncle>
		
		
		</uncle>
		
		<uncle>
		
		
		</uncle>
		<anut >
		
		</anut>
	</grandfather>
</family>
